export const ProgressSteps = {
  NO_SEARCH: 'NO_SEARCH',
  PENDING_1: 'PENDING_1',
  VIEWING_RESULT: 'VIEWING_RESULT',
  ERROR_1: 'ERROR_1',
  READING_INFO: 'READING_INFO',
  PENDING_2: 'PENDING_2',
  BOOKING_SUCCESS: 'BOOKING_SUCCESS',
  ERROR_2: 'ERROR_2',
};



