export const SEARCH_ORIGIN_CHANGE = 'SEARCH_ORIGIN_CHANGE';
export const SEARCH_ORIGIN_CLEAR = 'SEARCH_ORIGIN_CLEAR';
export const SEARCH_ORIGIN_SHOW_X = 'SEARCH_ORIGIN_SHOW_X';
export const SEARCH_ORIGIN_HIDE_X = 'SEARCH_ORIGIN_HIDE_X';

export const SEARCH_ORIGIN_ADDRESS_TEMP_CLEAR = 'SEARCH_ORIGIN_ADDRESS_TEMP_CLEAR';
export const SEARCH_ORIGIN_ADDRESS_START_FETCH = 'SEARCH_ORIGIN_ADDRESS_START_FETCH';
export const SEARCH_ORIGIN_ADDRESS_STOP_FETCH = 'SEARCH_ORIGIN_ADDRESS_STOP_FETCH';

export const SEARCH_DESTINATION_CHANGE = 'SEARCH_DESTINATION_CHANGE';
export const SEARCH_DESTINATION_CLEAR = 'SEARCH_DESTINATION_CLEAR';
export const SEARCH_DESTINATION_SHOW_X = 'SEARCH_DESTINATION_SHOW_X';
export const SEARCH_DESTINATION_HIDE_X = 'SEARCH_DESTINATION_HIDE_X';

export const SEARCH_DESTINATION_ADDRESS_TEMP_CLEAR = 'SEARCH_DESTINATION_ADDRESS_TEMP_CLEAR';
export const SEARCH_DESTINATION_ADDRESS_START_FETCH = 'SEARCH_DESTINATION_ADDRESS_START_FETCH';
export const SEARCH_DESTINATION_ADDRESS_STOP_FETCH = 'SEARCH_DESTINATION_ADDRESS_STOP_FETCH';

export const SEARCH_SWITCH_INPUTS = 'SEARCH_SWITCH_INPUTS';

export const SEARCH_ADD_DAY = 'SEARCH_ADD_DAY';
export const SEARCH_SUBTRACT_DAY = 'SEARCH_SUBTRACT_DAY';
export const SEARCH_ADD_TEN_MINUTES = 'SEARCH_ADD_TEN_MINUTES';
export const SEARCH_SUBTRACT_TEN_MINUTES = 'SEARCH_SUBTRACT_TEN_MINUTES';
export const SEARCH_CHANGE_TIMETARGET = 'SEARCH_CHANGE_TIMETARGET';
export const SEARCH_SET_TIME_TO_NOW = 'SEARCH_SET_TIME_TO_NOW';

export const SEARCH_FETCH_RESULT = 'SEARCH_FETCH_RESULT';
export const SEARCH_CANCEL_FETCH = 'SEARCH_CANCEL_FETCH';
export const SEARCH_RESULT_RECEIVED = 'SEARCH_RESULT_RECEIVED';
export const SEARCH_ERROR_RECEIVED = 'SEARCH_ERROR_RECEIVED';

export const MAP_REDO_FITBOUNDS = 'MAP_REDO_FITBOUNDS';
export const MAP_SET_ZOOMLEVEL = 'MAP_SET_ZOOMLEVEL';
export const MAP_SET_BOUNDS = 'MAP_SET_BOUNDS';
export const MAP_SET_CENTER = 'MAP_SET_CENTER';

export const MAP_RENDERING_START = 'MAP_RENDERING_START';
export const MAP_RENDERING_STOP = 'MAP_RENDERING_STOP';
